### ISSUE TITLE
Haha, your version is also start from 0.5

### ISSUE THREAD

**Issue by LongTengDao** [Lepzulnag/ion-parser#1]
I didn't intend to support any earlier version. Later I added support for 0.4, and found the version number was...

What's your plan?

**Comment by Lepzulnag** [comment]
Hey =)

No, I don’t intend neither to support a previous version. Maybe I would have done it if TOML was super-famous, but since it’s not (although in my opinion it deserves to be famous) I think we should rather look at the future versions rather than the past ones.



De : 龙腾道
Envoyé le :samedi 23 mars 2019 11:57
À : Lepzulnag/ion-parser
Cc : Subscribed
Objet :[Lepzulnag/ion-parser] Haha, your version is also start from 0.5 (#1)

I didn't intend to support any earlier version. Later I added support for 0.4, and found the version number was...
What's your plan?
